import type { PostCondition } from '@stacks/transactions';

export interface StateChangeDiff {
  asset: string;
  amount: number;
  direction: 'IN' | 'OUT';
}

export interface SimulationResult {
  success: boolean;
  predictedFee: number;
  postConditions: PostCondition[];
  humanReadableDiff: StateChangeDiff[];
  rawOutput?: string;
  /** Wallet call parameters generated by the registry plugin, passed through to the frontend */
  stxCallParams?: {
    contractAddress: string;
    contractName: string;
    functionName: string;
    functionArgs: string[];
  };
}

